# Generated by Django 2.2 on 2020-06-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPDATA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(max_length=100)),
                ('hostName', models.CharField(max_length=100)),
                ('loopback', models.CharField(max_length=100)),
                ('macid', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ip_info',
            },
        ),
    ]
